package Reviews::Model::EventsDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';
use FindBin;
# Events applications dir should be in the same directory
# of Reviews
use lib "$FindBin::Bin/../../Events/lib";


__PACKAGE__->config(
    schema_class => 'Events::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:dbname=events',
        user => 'root',
        password => '',
    }
);

=head1 NAME

Reviews::Model::EventsDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Reviews>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Reviews::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.53

=head1 AUTHOR



=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
